# Generated by Django 5.2.1 on 2025-08-19 19:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarioclub',
            options={'verbose_name': 'Calendario de club deportivo', 'verbose_name_plural': 'Calendarios de clubes deportivos'},
        ),
        migrations.AlterModelOptions(
            name='calendarioinstalacion',
            options={'verbose_name': 'Calendario de instalación deportiva', 'verbose_name_plural': 'Calendarios de instalaciones deportivas'},
        ),
        migrations.AlterModelOptions(
            name='calendariopista',
            options={'verbose_name': 'Calendario de pista', 'verbose_name_plural': 'Calendarios de pistas'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría de club', 'verbose_name_plural': 'Categorías de clubes'},
        ),
        migrations.AlterModelOptions(
            name='categoriaequipo',
            options={'verbose_name': 'Categoría de equipo', 'verbose_name_plural': 'Categorías de equipos'},
        ),
        migrations.AlterModelOptions(
            name='categoriajugador',
            options={'verbose_name': 'Categoría de jugador', 'verbose_name_plural': 'Categorías de jugadores'},
        ),
        migrations.AlterModelOptions(
            name='categoriapareja',
            options={'verbose_name': 'Categoría de pareja', 'verbose_name_plural': 'Categorías de parejas'},
        ),
        migrations.AlterModelOptions(
            name='clasejugador',
            options={'verbose_name': 'Asistencia a clase', 'verbose_name_plural': 'Asistencias a clases'},
        ),
        migrations.AlterModelOptions(
            name='claseprofesor',
            options={'verbose_name': 'Impartición de clase', 'verbose_name_plural': 'Imparticiones de clases'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club deportivo', 'verbose_name_plural': 'Clubes deportivos'},
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name': 'Configuración de club', 'verbose_name_plural': 'Configuraciones de clubes'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato de técnico con club', 'verbose_name_plural': 'Contratos de técnicos con clubes'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso impartido', 'verbose_name_plural': 'Cursos impartidos'},
        ),
        migrations.AlterModelOptions(
            name='dependencia',
            options={'verbose_name': 'Dependencia de instalación deportiva', 'verbose_name_plural': 'Dependencias de instalaciones deportivas'},
        ),
        migrations.AlterModelOptions(
            name='destinatarioclub',
            options={'verbose_name': 'Destinatario club', 'verbose_name_plural': 'Destinatarios clubes'},
        ),
        migrations.AlterModelOptions(
            name='destinatariocurso',
            options={'verbose_name': 'Destinatario curso', 'verbose_name_plural': 'Destinatarios cursos'},
        ),
        migrations.AlterModelOptions(
            name='destinatariodirectivo',
            options={'verbose_name': 'Destinatario directivo', 'verbose_name_plural': 'Destinatarios directivos'},
        ),
        migrations.AlterModelOptions(
            name='destinatarioequipo',
            options={'verbose_name': 'Destinatario equipo', 'verbose_name_plural': 'Destinatarios equipos'},
        ),
        migrations.AlterModelOptions(
            name='destinatarioinstalacion',
            options={'verbose_name': 'Destinatario instalación deportiva', 'verbose_name_plural': 'Destinatarios instalaciones deportivas'},
        ),
        migrations.AlterModelOptions(
            name='destinatariojugador',
            options={'verbose_name': 'Destinatario jugador', 'verbose_name_plural': 'Destinatarios jugadores'},
        ),
        migrations.AlterModelOptions(
            name='destinatariopareja',
            options={'verbose_name': 'Destinatario pareja', 'verbose_name_plural': 'Destinatarios parejas'},
        ),
        migrations.AlterModelOptions(
            name='destinatariopista',
            options={'verbose_name': 'Destinatario pista', 'verbose_name_plural': 'Destinatarios pistas'},
        ),
        migrations.AlterModelOptions(
            name='destinatariotecnico',
            options={'verbose_name': 'Destinatario técnico', 'verbose_name_plural': 'Destinatarios técnicos'},
        ),
        migrations.AlterModelOptions(
            name='destinatariotorneodobles',
            options={'verbose_name': 'Destinatario torneo de dobles', 'verbose_name_plural': 'Destinatarios torneos de dobles'},
        ),
        migrations.AlterModelOptions(
            name='destinatariotorneoequipos',
            options={'verbose_name': 'Destinatario torneo por equipos', 'verbose_name_plural': 'Destinatarios torneos por equipos'},
        ),
        migrations.AlterModelOptions(
            name='destinatariotorneoindividual',
            options={'verbose_name': 'Destinatario torneo individual', 'verbose_name_plural': 'Destinatarios torneos individuales'},
        ),
        migrations.AlterModelOptions(
            name='directivo',
            options={'verbose_name': 'Directivo de club', 'verbose_name_plural': 'Directivos de clubes'},
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'verbose_name': 'Envío de mensaje', 'verbose_name_plural': 'Envíos de mensajes'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='estadoclase',
            options={'verbose_name': 'Estado de una clase', 'verbose_name_plural': 'Estados de una clase'},
        ),
        migrations.AlterModelOptions(
            name='estadoenvio',
            options={'verbose_name': 'Estado de un envío', 'verbose_name_plural': 'Estados de un envío'},
        ),
        migrations.AlterModelOptions(
            name='estadoinscripcion',
            options={'verbose_name': 'Estado de una inscripción', 'verbose_name_plural': 'Estados de una inscripción'},
        ),
        migrations.AlterModelOptions(
            name='estadopartido',
            options={'verbose_name': 'Estado de un partido', 'verbose_name_plural': 'Estados de un partido'},
        ),
        migrations.AlterModelOptions(
            name='etapa',
            options={'verbose_name': 'Etapa de técnico en equipo', 'verbose_name_plural': 'Etapas de técnicos en equipos'},
        ),
        migrations.AlterModelOptions(
            name='horarioclub',
            options={'verbose_name': 'Horario de club', 'verbose_name_plural': 'Horarios de clubes'},
        ),
        migrations.AlterModelOptions(
            name='horarioinstalacion',
            options={'verbose_name': 'Horario de instalación deportiva', 'verbose_name_plural': 'Horarios de instalaciones deportivas'},
        ),
        migrations.AlterModelOptions(
            name='horariopista',
            options={'verbose_name': 'Horario de pista', 'verbose_name_plural': 'Horarios de pistas'},
        ),
        migrations.AlterModelOptions(
            name='inscripcionequipo',
            options={'verbose_name': 'Inscripción de equipo en torneo', 'verbose_name_plural': 'Inscripciones de equipos en torneos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcionjugador',
            options={'verbose_name': 'Inscripción de jugador en torneo', 'verbose_name_plural': 'Inscripciones de jugadores en torneos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcionpareja',
            options={'verbose_name': 'Inscripción de pareja en torneo', 'verbose_name_plural': 'Inscripciones de parejas en torneos'},
        ),
        migrations.AlterModelOptions(
            name='instalacion',
            options={'verbose_name': 'Instalación deportiva', 'verbose_name_plural': 'Instalaciones deportivas'},
        ),
        migrations.AlterModelOptions(
            name='mandato',
            options={'verbose_name': 'Mandato de directivo en club', 'verbose_name_plural': 'Mandatos de directivos en clubes'},
        ),
        migrations.AlterModelOptions(
            name='matriculajugador',
            options={'verbose_name': 'Matrícula de jugador en curso', 'verbose_name_plural': 'Matrículas de jugadores en cursos'},
        ),
        migrations.AlterModelOptions(
            name='membresia',
            options={'verbose_name': 'Membresía de jugador en equipo', 'verbose_name_plural': 'Membresías de jugadores en equipos'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='partidodobles',
            options={'verbose_name': 'Partido de dobles', 'verbose_name_plural': 'Partidos de dobles'},
        ),
        migrations.AlterModelOptions(
            name='partidoindividual',
            options={'verbose_name': 'Partido individual', 'verbose_name_plural': 'Partidos individuales'},
        ),
        migrations.AlterModelOptions(
            name='pertenencia',
            options={'verbose_name': 'Pertenencia de jugador a club', 'verbose_name_plural': 'Pertenencias de jugadores a clubes'},
        ),
        migrations.AlterModelOptions(
            name='posesion',
            options={'verbose_name': 'Posesión', 'verbose_name_plural': 'Posesiones'},
        ),
        migrations.AlterModelOptions(
            name='rankingjugadorclub',
            options={'verbose_name': 'Ranking de jugador en club', 'verbose_name_plural': 'Rankings de jugadores en clubes'},
        ),
        migrations.AlterModelOptions(
            name='rankingjugadortorneo',
            options={'verbose_name': 'Ranking de jugador en torneo', 'verbose_name_plural': 'Rankings de jugadores en torneos'},
        ),
        migrations.AlterModelOptions(
            name='rankingparejaclub',
            options={'verbose_name': 'Ranking de pareja en club', 'verbose_name_plural': 'Rankings de parejas en clubes'},
        ),
        migrations.AlterModelOptions(
            name='rankingparejatorneo',
            options={'verbose_name': 'Ranking de pareja en torneo', 'verbose_name_plural': 'Rankings de parejas en torneos'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='reservaclub',
            options={'verbose_name': 'Reserva de club', 'verbose_name_plural': 'Reservas de clubes'},
        ),
        migrations.AlterModelOptions(
            name='reservacurso',
            options={'verbose_name': 'Reserva de curso', 'verbose_name_plural': 'Reservas de cursos'},
        ),
        migrations.AlterModelOptions(
            name='reservajugador',
            options={'verbose_name': 'Reserva de jugador', 'verbose_name_plural': 'Reservas de jugadores'},
        ),
        migrations.AlterModelOptions(
            name='reservatorneodobles',
            options={'verbose_name': 'Reserva de torneo de dobles', 'verbose_name_plural': 'Reservas de torneos de dobles'},
        ),
        migrations.AlterModelOptions(
            name='reservatorneoequipos',
            options={'verbose_name': 'Reserva de torneo por equipos', 'verbose_name_plural': 'Reservas de torneos por equipos'},
        ),
        migrations.AlterModelOptions(
            name='reservatorneoindividual',
            options={'verbose_name': 'Reserva de torneo individual', 'verbose_name_plural': 'Reservas de torneos individuales'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'verbose_name': 'Técnico', 'verbose_name_plural': 'Técnicos'},
        ),
        migrations.AlterModelOptions(
            name='tipocalendario',
            options={'verbose_name': 'Tipo de calendario', 'verbose_name_plural': 'Tipos de calendario'},
        ),
        migrations.AlterModelOptions(
            name='tipocontrato',
            options={'verbose_name': 'Tipo de contrato', 'verbose_name_plural': 'Tipos de contrato'},
        ),
        migrations.AlterModelOptions(
            name='tipocurso',
            options={'verbose_name': 'Tipo de curso', 'verbose_name_plural': 'Tipos de curso'},
        ),
        migrations.AlterModelOptions(
            name='tipodependencia',
            options={'verbose_name': 'Tipo de dependencia', 'verbose_name_plural': 'Tipos de dependencia'},
        ),
        migrations.AlterModelOptions(
            name='tipodirectivo',
            options={'verbose_name': 'Tipo de directivo', 'verbose_name_plural': 'Tipos de directivo'},
        ),
        migrations.AlterModelOptions(
            name='tipolateralidad',
            options={'verbose_name': 'Tipo de lateralidad', 'verbose_name_plural': 'Tipos de lateralidad'},
        ),
        migrations.AlterModelOptions(
            name='tipomembresia',
            options={'verbose_name': 'Tipo de membresía', 'verbose_name_plural': 'Tipos de membresía'},
        ),
        migrations.AlterModelOptions(
            name='tipomensaje',
            options={'verbose_name': 'Tipo de mensaje', 'verbose_name_plural': 'Tipos de mensaje'},
        ),
        migrations.AlterModelOptions(
            name='tipotitulacion',
            options={'verbose_name': 'Tipo de titulación', 'verbose_name_plural': 'Tipos de titulación'},
        ),
        migrations.AlterModelOptions(
            name='torneodobles',
            options={'verbose_name': 'Torneo de dobles', 'verbose_name_plural': 'Torneos de dobles'},
        ),
        migrations.AlterModelOptions(
            name='torneoequipos',
            options={'verbose_name': 'Torneo por equipos', 'verbose_name_plural': 'Torneos por equipos'},
        ),
        migrations.AlterModelOptions(
            name='torneoindividual',
            options={'verbose_name': 'Torneo individual', 'verbose_name_plural': 'Torneos individuales'},
        ),
        migrations.AlterField(
            model_name='club',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='token_qr_global',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='aplicacion_futura',
            field=models.BooleanField(db_comment='¿Se aplica a nuevos miembros?'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='pareja',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='partidodobles',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='partidodobles',
            name='token_qr_confirmacion',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='partidoindividual',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='partidoindividual',
            name='token_qr_confirmacion',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='pista',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='torneodobles',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='torneoequipos',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='torneoindividual',
            name='token_qr',
            field=models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True),
        ),
    ]
