# Generated by Django 5.2.1 on 2025-08-21 00:22

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_calendarioclub_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCapacitacion',
            fields=[
                ('id_tipo_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de capacitación',
                'verbose_name_plural': 'Tipos de capacitación',
                'db_table': 'tipo_capacitacion',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleo',
            fields=[
                ('id_tipo_empleo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de empleo',
                'verbose_name_plural': 'Tipos de empleo',
                'db_table': 'tipo_empleo',
            },
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato [técnico-club]', 'verbose_name_plural': 'Contratos [técnico-club]'},
        ),
        migrations.AlterModelOptions(
            name='etapa',
            options={'verbose_name': 'Etapa [técnico-equipo]', 'verbose_name_plural': 'Etapas [técnico-equipo]'},
        ),
        migrations.AlterModelOptions(
            name='mandato',
            options={'verbose_name': 'Mandato [directivo-club]', 'verbose_name_plural': 'Mandatos [directivo-club]'},
        ),
        migrations.AlterModelOptions(
            name='matriculajugador',
            options={'verbose_name': 'Matrícula [jugador-curso]', 'verbose_name_plural': 'Matrículas [jugador-curso]'},
        ),
        migrations.AlterModelOptions(
            name='membresia',
            options={'verbose_name': 'Membresía [jugador-equipo]', 'verbose_name_plural': 'Membresías [jugador-equipo]'},
        ),
        migrations.AlterModelOptions(
            name='pertenencia',
            options={'verbose_name': 'Pertenencia [jugador-club]', 'verbose_name_plural': 'Pertenencias [jugador-club]'},
        ),
        migrations.AlterModelOptions(
            name='posesion',
            options={'verbose_name': 'Posesión [instalación-club]', 'verbose_name_plural': 'Posesiones [instalación-club]'},
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id_operario', models.AutoField(primary_key=True, serialize=False)),
                ('token_qr', models.CharField(default=core.models.nuevo_token_qr, max_length=32, unique=True)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.RESTRICT, to='core.persona')),
                ('id_tipo_capacitacion', models.ForeignKey(db_column='id_tipo_capacitacion', on_delete=django.db.models.deletion.RESTRICT, to='core.tipocapacitacion')),
            ],
            options={
                'verbose_name': 'Operario',
                'verbose_name_plural': 'Operarios',
                'db_table': 'operario',
            },
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id_empleo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_instalacion', models.ForeignKey(db_column='id_instalacion', on_delete=django.db.models.deletion.RESTRICT, to='core.instalacion')),
                ('id_operario', models.ForeignKey(db_column='id_operario', on_delete=django.db.models.deletion.RESTRICT, to='core.operario')),
                ('id_tipo_empleo', models.ForeignKey(db_column='id_tipo_empleo', on_delete=django.db.models.deletion.RESTRICT, to='core.tipoempleo')),
            ],
            options={
                'verbose_name': 'Empleo [operario-instalación]',
                'verbose_name_plural': 'Empleos [operario-instalación]',
                'db_table': 'empleo',
            },
        ),
    ]
