# Generated by Django 5.2.1 on 2025-08-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipocapacitacion_tipoempleo_alter_contrato_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinatarioclub',
            options={'verbose_name': 'Destinatario [club]', 'verbose_name_plural': 'Destinatarios [club]'},
        ),
        migrations.AlterModelOptions(
            name='destinatariocurso',
            options={'verbose_name': 'Destinatario [curso]', 'verbose_name_plural': 'Destinatarios [curso]'},
        ),
        migrations.AlterModelOptions(
            name='destinatariodirectivo',
            options={'verbose_name': 'Destinatario [directivo]', 'verbose_name_plural': 'Destinatarios [directivo]'},
        ),
        migrations.AlterModelOptions(
            name='destinatarioequipo',
            options={'verbose_name': 'Destinatario [equipo]', 'verbose_name_plural': 'Destinatarios [equipo]'},
        ),
        migrations.AlterModelOptions(
            name='destinatarioinstalacion',
            options={'verbose_name': 'Destinatario [instalación]', 'verbose_name_plural': 'Destinatarios [instalación]'},
        ),
        migrations.AlterModelOptions(
            name='destinatariojugador',
            options={'verbose_name': 'Destinatario [jugador]', 'verbose_name_plural': 'Destinatarios [jugador]'},
        ),
        migrations.AlterModelOptions(
            name='destinatariopareja',
            options={'verbose_name': 'Destinatario [pareja]', 'verbose_name_plural': 'Destinatarios [pareja]'},
        ),
        migrations.AlterModelOptions(
            name='destinatariopista',
            options={'verbose_name': 'Destinatario [pista]', 'verbose_name_plural': 'Destinatarios [pista]'},
        ),
        migrations.AlterModelOptions(
            name='destinatariotecnico',
            options={'verbose_name': 'Destinatario [técnico]', 'verbose_name_plural': 'Destinatarios [técnico]'},
        ),
        migrations.AlterModelOptions(
            name='destinatariotorneodobles',
            options={'verbose_name': 'Destinatario [torneo dobles]', 'verbose_name_plural': 'Destinatarios [torneo dobles]'},
        ),
        migrations.AlterModelOptions(
            name='destinatariotorneoequipos',
            options={'verbose_name': 'Destinatario [torneo equipos]', 'verbose_name_plural': 'Destinatarios [torneo equipos]'},
        ),
        migrations.AlterModelOptions(
            name='destinatariotorneoindividual',
            options={'verbose_name': 'Destinatario [torneo individual]', 'verbose_name_plural': 'Destinatarios [torneo individual]'},
        ),
        migrations.CreateModel(
            name='DestinatarioOperario',
            fields=[
                ('id_destinatario_operario', models.AutoField(primary_key=True, serialize=False)),
                ('id_mensaje', models.ForeignKey(db_column='id_mensaje', on_delete=django.db.models.deletion.RESTRICT, to='core.mensaje')),
                ('id_operario', models.ForeignKey(db_column='id_operario', on_delete=django.db.models.deletion.RESTRICT, to='core.operario')),
                ('id_tipo_mensaje', models.ForeignKey(blank=True, db_column='id_tipo_mensaje', db_comment='Por si se quiere hacer override del tipo', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.tipomensaje')),
            ],
            options={
                'verbose_name': 'Destinatario [operario]',
                'verbose_name_plural': 'Destinatarios [operario]',
                'db_table': 'destinatario_operario',
            },
        ),
    ]
